---
title: "Better Campsites"
author: "Julia Lee"
date: "3/31/2018"
output: 
  html_document:
    code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

#install.packages("sf")
library(sf)
#install.packages("macleish")
#devtools::install_github("beanumber/macleish")
library(macleish)
library(leaflet)
library(RSQLite)
#install.packages("lwgeom")
library(lwgeom)

devtools::install_github("beanumber/macleish")
library(macleish)
packageVersion("macleish")

```

```{r, message=FALSE, warning=FALSE}
landmarks<-macleish_layers[["landmarks"]]
trail<-macleish_layers[["trails"]]

#adding stream length
streams <- macleish_layers[["streams"]]%>%
mutate(Length_Of_Streams = st_length(geometry))
```

```{r,message=FALSE,warning=FALSE}
#adding trail length
trails<-macleish_layers[["trails"]] %>%
  mutate(Length_Of_Trails = st_length(geometry))

#intersection of boundary and trails
inside_trails<-st_intersection(macleish_layers[["boundary"]],trails)
```

```{r,message=FALSE,warning=FALSE}
#intersection of boundary and streams
inside_streams<-st_intersection(macleish_layers[["boundary"]],
              streams)
```

```{r,message=FALSE,warning=FALSE}
#intersection of trails and streams and boundary 
streams_trails<-st_intersection(inside_trails,inside_streams)

trail_stream_crossing <- st_cast(streams_trails, "POINT")
```

```{r,message=FALSE,warning=FALSE}
# making a table of important places
sites <- tribble(
~point, ~lat, ~lon,
"Group Campsite", 42.450976, -72.678154,
"Remote Campite", 42.458549, -72.679581,
"Parking", 42.448013, -72.680663)
places <- st_as_sf(sites,coords = c("lon", "lat"), crs = 4326)
```




```{r, message=FALSE, warning = FALSE}
#contour_file 
contour <-"http://download.massgis.digital.mass.gov/shapefiles/state/contours250k.zip"
contour_file <- basename(contour)
download.file(contour, destfile = contour_file)
unzip(contour_file, exdir ="contours250k")
contour <- path.expand("contours250k")
contour_lines <-st_read("CONTOURS250K_ARC.shp")
contour_lines%>%
plot()
```

```{r, message=FALSE,warning=FALSE}
#Possible campsites
possible_camps <- tribble(
~point, ~lat, ~lon,
"camp_A",42.4478582225726, -72.6741503904343483,
 "camp_B",42.44503189520893, -72.6787624426988,
"camp_C",42.45024,-72.68299)
campsites<-st_as_sf(possible_camps,coords = c("lon", "lat"), crs = 4326)
```

```{r,message=FALSE, warning=FALSE}
forests<-macleish_layers[["forests"]] %>%
  rename(type_of_forest = Sheet1__Na) %>%
   mutate(Area = st_area(geometry))
research<-macleish_layers[["research"]]
color1<-colorFactor("Paired", inside_trails$name)

color2 <-colorBin("Reds", inside_streams$Length_Of_Streams,5, pretty = FALSE)

color3<-colorFactor("Dark2", forests$type_of_forest)

```

```{r, message=FALSE, warning=FALSE }
map<-leaflet() %>%
  addTiles() %>%
  #plotting important locations (parking lot, ground campsite, remote campsite)
  addMarkers(data = places, popup = ~point) %>%
  #putting the new campsites on the map 
  addMarkers(data = campsites, popup = ~point) 
```

```{r, message=FALSE, warning=FALSE }
map<-map%>%
  #adding the boundary layer 
  addPolygons(data = macleish_layers[["boundary"]], 
              weight = 0.5, color = "lightyellow", group = "boundary") 
```

```{r, message=FALSE, warning=FALSE }
map<-map %>% 
  #adding the challenge courses to map      
  addCircles(data =
      macleish_layers[["challenge_courses"]], 
              weight = 1,popup = "Challenge Course", color = "green", group = "challenge_course") %>%
  #only mapping the streams that are inside the boundary of MacLeish
  addPolylines(data = inside_streams, weight= 5, popup =  ~Id, color = "Gray", group = "water_source") 
```

```{r, message=FALSE, warning=FALSE }
map<-map %>%
  #mapping the trails and coloring them based on name and adding a popup to show the name of each trail by clicking on it
  addPolylines(data = inside_trails, weight = 5, popup =  ~name, color = ~color1(name), group = "trail") 
```


```{r, message=FALSE, warning=FALSE }
map<-map%>%
  #adding wetlands layer
  addPolygons(data = macleish_layers[["wetlands"]], 
              weight = 1, fillOpacity = 0.2, popup = ~SOURCE, color = "dodgerblue", group = "water_source") %>%
  #adding landmarks
  addCircles(data = macleish_layers[["landmarks"]], 
              weight = 2, fillOpacity = 0.2, popup = ~Label, color = "orange", group = "landmark") 
  
```


```{r, message=FALSE, warning=FALSE}
map <- map %>%
  #adding forest layer and coloring by type of forest and adding popups that tell the map user what kind of forest
   addPolygons(data = forests, 
              weight = 1, fillOpacity = 0.1, color =~color3(type_of_forest), popup = ~type_of_forest, group = "forests")
```


```{r, message=FALSE, warning=FALSE}
map <- map %>%
  #adding building layer
  addPolygons(data = macleish_layers[["buildings"]], weight = 1, popup = ~name, group = "buildings") %>%
  #adding research locations, popups are by name of research project
  addPolygons (data = research, popup = ~Name, weight = 1, color = "Black") 
```


```{r, message=FALSE, warning=FALSE}
map <- map %>%
#Add contour line
  addPolylines(data = macleish_layers[["contours_30ft"]], group ="lines" ) %>%
  addProviderTiles("Esri.WorldTopoMap", group = "lines") %>%
  #Layers control
addLayersControl(
    baseGroups = c("lines"),
    overlayGroups = c("boundary", "buildings", "water_source", "forests","landmark","challenge_course","trail"),
    options = layersControlOptions(collapsed = FALSE)
  ) 
map 
```

```{r, message=FALSE,warning=FALSE}
#finding the distance between campsites and parking
PARKING <- data.frame(lon = -72.680663 , lat = 42.448013) %>% 
 st_as_sf(coords = c("lon", "lat"), crs = 4326)
camp_A<- data.frame(lat = 42.4478582225726, lon =
-72.674103904343483)%>% 
 st_as_sf(coords = c("lon", "lat"), crs = 4326)


camp_C<-data.frame(lat =42.45024, lon = -72.68299)%>% 
 st_as_sf(coords = c("lon", "lat"), crs = 4326)

camp_B <- data.frame(lon = -72.6787624426988 , lat = 42.44503189520893) %>% 
 st_as_sf(coords = c("lon", "lat"), crs = 4326)

st_distance(camp_B, PARKING, crs = 4326)
st_distance(camp_A, PARKING, crs = 4326)
st_distance(camp_C, PARKING, crs = 4326)

```








